### ISSUE TITLE
关于修改输入文件中的元素种类的询问

### ISSUE THREAD

**Issue by Wanghy02** [caimeiniu/pyhea#11]
老师您好，在安装完程序之后，例如我想生成CrFeCoNiCu高熵合金64个原子的原胞，要怎样修改config.yalm或者其他输入文件才能运行呢？

**Comment by caimeiniu** [comment]
你好，目前代码中的实现只覆盖了立方晶胞（cell_dim必须要相等）的体系，所以对于 FCC 构型来说，可选的原子数为 4 * 2^3 = 32个；或者 4 * 3^3 = 108 个，以此类推，比较遗憾暂时还不支持64个原子体系。相对应的32原子体系的可能参考输入文件如下（需要保持element加起来的原子总数=cell_dim计算出的原子总数）：

```
type: 5
element:
  - 6
  - 6
  - 6
  - 6
  - 8
cell_dim:
  - 2
  - 2
  - 2
device: gpu
solutions: 128
total_iter: 10
parallel_task: 256
converge_depth: 10
weight:
  - 4.0
  - 0.1
  - 0.1
# target_sro: TARGET_SRO
structure: POSCAR_FCC
output:
  name: conf           # Output file name, default: output
  format: lammps/lmp   # Supported formats: vasp/poscar(default), lammps/lmp
```
